CREATE SCHEMA IF NOT EXISTS ORGANIZER;

CREATE TABLE IF NOT EXISTS ORGANIZER.PERSON(
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(128) UNIQUE NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED_TIME TIMESTAMP,
);


CREATE TABLE IF NOT EXISTS ORGANIZER.FAMILY(
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(128) UNIQUE NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED_TIME TIMESTAMP,
);


CREATE TABLE IF NOT EXISTS ORGANIZER.FAMILY_MEMBER(
  ID SERIAL PRIMARY KEY NOT NULL,
  FAMILY_ID INT NOT NULL,
  PERSON_ID INT NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (FAMILY_ID) REFERENCES ORGANIZER.FAMILY(ID),
  FOREIGN KEY (PERSON_ID) REFERENCES ORGANIZER.PERSON(ID)
);


CREATE INDEX IF NOT EXISTS IX_FAMILY_MEMBER_PERSON_ID ON ORGANIZER.FAMILY_MEMBER (PERSON_ID);
CREATE INDEX IF NOT EXISTS IX_FAMILY_MEMBER_FAMILY_ID ON ORGANIZER.FAMILY_MEMBER (FAMILY_ID);
CREATE UNIQUE INDEX IF NOT EXISTS UIX_FAMILY_MEMBER_FAMILY_ID_PERSON_ID ON ORGANIZER.FAMILY_MEMBER (FAMILY_ID, PERSON_ID);